version: '2'
services:
    ijolanauth-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/ijolanauth/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=ijolanauth
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
